version: '2'

services:
  mongo:
    image: mongo:3.4-jessie
    ports:
      - 27017:27017
    expose:
      - 27017
    container_name: mongo
    network_mode: host
  eureka-server:
    build: eurekaservice/
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8761:8761

  config-service:
    build: config/
    restart: always
    network_mode: "host"
    image: demo-config-service
    hostname: localhost
    ports:
      - 8888:8888

  zuul-apigateway:
    build: zuulService/
    depends_on:
      - config-service
      - eureka-server
      - user-service
    restart: always
    network_mode: "host"

    hostname: localhost
    ports:
      - 8085:8085

  user-service:
    build: user-service/
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8081:8081
    depends_on:
      - config-service
      - eureka-server


